[tool.isort]
# Avoid conflicts between local folders and pypi packages
known_first_party = [
    "app",
    "common",
    "models",
    "utils",
    "eval_config",
    "build_config",
    "controllers",
    "config",
    "metrics",
    "settings"
]
# This is arguably wrong, but this was configured like this in the past,
# so keeping them to avoid noise changes.
known_third_party = ["uuid", "enum"]
skip_glob = "**/build/**,frontends/**,legacy/**"
combine_as_imports = true
lines_after_imports = 2
# Make isort compatible with black
profile = "black"

[tool.black]
line-length = 88
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | website
)/
'''
