import React, { FC, useState } from "react";
import Modal from "react-bootstrap/Modal";

type SignContractProps = {
  handleClose: () => void;
};

const SignContract: FC<SignContractProps> = ({ handleClose }) => {
  return (
    <div className="p-4 rounded-lg">
      <Modal.Header closeButton>
        <Modal.Title className="text-2xl font-bold text-letter-color">
          Consent
        </Modal.Title>
      </Modal.Header>
      <Modal.Body>
        <div className="overflow-auto max-h-64">
          <p className="text-sm text-letter-color">
            <p className="font-bold text-[#e67e23]">
              {" "}
              Please then read through this information before agreeing to
              participate (if you wish to) by ticking the 'yes' box below.
            </p>
            <br />
            You may ask any questions before deciding to take part by contacting
            the research team. The Principal Researcher is Hannah Rose Kirk, and
            the Principle Investigator is Dr Scott. A. Hale, who are both
            affiliated with the Oxford Internet Institute at the University of
            Oxford. <br /> <br />
            What does the task involve? <br /> You will have conversations with
            AI language models by providing prompts and rating their responses.
            The prompts can be on various topics, and you don't need any
            specific knowledge to participate. Your input will help us
            understand your preferences and opinions about how these AI language
            models work. No background knowledge is required.
            <br /> <br />{" "}
            <p className="font-bold text-[#e67e23]">
              Please note that you will be interacting with an AI language
              model. The research team cannot directly control and are not
              responsible for the text generated by these models. There is a
              possibility that the models produce biased, inaccurate or harmful
              language. The risks to you as an individual are equivalent to
              those you would be exposed to if you use AI language models via
              interfaces like ChatGPT.
            </p>
            <br /> <br /> Do I have to take part? <br /> No, participation is
            voluntary. If you do decide to take part, you may stop at any point
            for any reason before submitting your answers by closing the
            browser.
            <br /> <br /> Can I withdraw my participation and data?
            <br /> Yes, you can withdraw your data from the study. The cut-off
            date for withdrawing your data is 14 days after you submitted the
            data. Please email members of the research team (see contact details
            below) within this 14-day window to withdraw your data from the
            study.
            <br /> <br /> How will my data be used?
            <br /> The data collected from your participation will be
            pseudo-anonymized (stored with a unique numeric ID) and stored
            securely. It will be used for research purposes, and your personal
            information will remain confidential. The data will be analysed to
            gain insights into diverse preferences and perceptions regarding AI
            language model behaviours. At the end of the study, the
            pseudo-anonymised data collected will be released publicly for
            future research. The findings of this study may be published in
            academic journals or presented at conferences, and the results will
            be written up for a DPhil degree. Your individual identity will not
            be disclosed at any point in data release or publication.
            <br /> <br /> We do not collect any personal, private identifying
            information, IP addresses or contact details. We will take all
            reasonable measures to ensure that data remain confidential.
            <br /> <br /> The responses you provide will be stored in a
            password-protected electronic file on University of Oxford secure
            servers and may be used in academic publications, conference
            presentations or reports for external organisations. We will release
            a clean, PII and pseudo-anonymised form of the data on an
            open-access, public data repository. Raw research data will be
            stored for 3 years after publication or public release of the
            research.
            <br /> <br /> We would like to use the data in future studies, and
            to share data with other researchers (e.g. in online databases).
            Data will have identifying information removed before it is shared
            with other researchers or results are made public. <br /> <br /> The
            data that we collect from you may be transferred to, stored and/ or
            processed at a destination outside the UK and the European Economic
            Area. By submitting your personal data, you agree to this transfer,
            storing or processing.
            <br /> <br />
            Who has reviewed this research?
            <br /> This research has been reviewed by, and received ethics
            clearance through, a subcommittee of the University of Oxford
            Central University Research Ethics Committee [OII_C1A_23_088].
            <br /> <br /> Who do I contact if I have a concern or I wish to
            complain?
            <br /> If you have a concern about any aspect of this research,
            please speak to Hannah Rose Kirk (hannah.kirk@oii.ox.ac.uk) or their
            supervisor Dr Scott A. Hale (scott.hale@oii.ox.ac.uk), and we will
            do our best to answer your query. We will acknowledge your concern
            within 10 working days and give you an indication of how it will be
            dealt with. If you remain unhappy or wish to make a formal
            complaint, please contact the Chair of the Research Ethics Committee
            at the University of Oxford who will seek to resolve the matter as
            soon as possible:
            <br /> <br />
            Social Sciences & Humanities Interdivisional Research Ethics
            Committee; Email: ethics@socsci.ox.ac.uk; Address: Research
            Services, University of Oxford, Boundary Brook House, Churchill
            Drive, Headington, Oxford OX3 7GB.
          </p>
        </div>
      </Modal.Body>
      <Modal.Footer>
        <div className="my-3 form-check">
          <input
            type="checkbox"
            className="form-check-input"
            onClick={handleClose}
          />
          <label className="form-check-label text-letter-color">
            I agree to the terms and conditions
          </label>
        </div>
      </Modal.Footer>
    </div>
  );
};

export default SignContract;
