metadata_url: "https://storage.googleapis.com/public-datasets-mswc/metadata.json.gz"
embeddings_url: "https://drive.google.com/file/d/1Lj1l7-FxipKF6ZtVpy7nSRMEWMD2yfCd/view"
# dataset_url: "https://storage.googleapis.com/public-datasets-mswc/mswc_microset.tar.gz"
